### ISSUE TITLE
underscore-map does not exist

### ISSUE THREAD

**Issue by mokkabonna** [ddopson/underscore-cli#26]
running one of the examples with map

```
echo '[1, 2, 3, 4]' | underscore map 'value+1'
```

I get this error

```
execvp(): No such file or directory
    underscore-map(1) does not exist, try --help
[2, 3, 4, 5]
```

Well it does also work, as it produces the right result, but I'd prefer it without the other output.

**Comment by budmc29** [comment]
I get the same error: node: No such file or directory.
Os: Ubuntu 14.04
Latest nodejs
