### ISSUE TITLE
Feature request: command-line option to control wrapWidth

### ISSUE THREAD

**Issue by davidmc24** [ddopson/underscore-cli#38]
It looks to me like `stringify` supports a `wrapWidth` config entry that adjusts the width that's allowed before wrapping.  This configuration is used in the `json` and `pretty` output formats.  However, unless I'm missing it, there's no way on the command-line to adjust it, and there are cases where I sometimes want something other than the default of `100`.

I'd like there to be a `--wrap-width` command-line argument to support adjusting it, similar to how the `--color` flag works.

**Comment by ajbw** [comment]
FYI I've just created #43 to add a --wrapwidth option, cause I need this too --- it works with the json & pretty outfmts.  Let me know if it works for you.

**Comment by ddopson** [comment]
Looks like I merged that PR in.  So this issue is probably addressed.  Reopen if otherwise.
