### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by kmsquire** [ddopson/underscore-cli#40]
I'd like to port your JSON printing code to Julia (for use in https://github.com/JuliaLang/JSON.jl).  

That code is MIT licensed, and porting is considered a derivative work.  Since you don't have a license on this code, can I have permission to release a port of your printing code under an MIT license?  

You also might consider adding a license to this code. (See https://help.github.com/articles/open-source-licensing/)

Cheers!

**Comment by kmsquire** [comment]
Also: http://stackoverflow.com/questions/5521080/can-i-use-the-code-in-a-github-project-which-does-not-have-a-license-specified

**Comment by kmsquire** [comment]
Bump?

**Comment by ddopson** [comment]
Hey, sorry, Github doesn't notify me when I get important messages.  Email me at (my-username) at gmail.  I'm sure we can figure something out.  I'd be curious what you want to accomplish (just curious; I'll give you a license either way). Would be awesome to have attribution in the new source code wherever is appropriate.

I can put an actual license on my repo too.  I'm in a rush this moment, maybe I can deal with it this weekend.

**Comment by ddopson** [comment]
Actually, looks like I did add a LICENSE file to this repo.  So this issue should be addressed.
