### ISSUE TITLE
Installation issue with msgpack or node-gyp 

### ISSUE THREAD

**Issue by emigenix** [ddopson/underscore-cli#55]
I'm getting the following `gyp ERR!` when trying to install using:
```sh 
$ npm install -g underscore-cli
C:\mybin\nodejs\underscore -> C:\mybin\nodejs\node_modules\underscore-cli\bin\underscore

> msgpack@1.0.2 install C:\mybin\nodejs\node_modules\underscore-cli\node_modules\msgpack
> node-gyp rebuild


C:\mybin\nodejs\node_modules\underscore-cli\node_modules\msgpack>if not defined npm_config_node_gyp (node "C:\mybin\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (C:\mybin\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:449:14)
gyp ERR! stack     at C:\mybin\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:404:11
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:123:15)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "C:\\mybin\\nodejs\\node.exe" "C:\\mybin\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\mybin\nodejs\node_modules\underscore-cli\node_modules\msgpack
gyp ERR! node -v v6.4.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
npm WARN install:msgpack@1.0.2 msgpack@1.0.2 install: `node-gyp rebuild`
npm WARN install:msgpack@1.0.2 Exit status 1
C:\mybin\nodejs
`-- underscore-cli@0.2.19
  +-- coffee-script@1.10.0
  +-- commander@1.0.5
  | `-- keypress@0.1.0
  +-- JSONSelect@0.4.0
  +-- underscore@1.8.3
  `-- underscore.string@3.2.3
```

However, `underscore-cli` seem to work anyway. I see this is a very old issue as it is present in many other forms in the closed issues. It doesn't make sense to close issues if they're neither resolved nor explained. BTW, python is present under `npm config get python` as */usr/bin/python*.  I'm using Cygwin on W8.1 with: 
```sh
$ node -v && npm -v
v6.4.0
3.10.6
```

**Comment by emigenix** [comment]
@ddopson Can we assume from the silence that this package is no longer maintained?

**Comment by emigenix** [comment]
Apparently this is a `node-gyp` issue, where there is an issue in the `../node-gyp/lib/configure.js` for checking the `python`.

**Comment by ddopson** [comment]
Yeah, I don't really do much on this package these days as I don't use node for anything. :(

I'd be happy to make you a maintainer if you're interested.

**Comment by emigenix** [comment]
@ddopson  Hi, and thanks for the response and invitation. I'm unfortunately quite new to node myself, so I don't think I'd be qualified to maintain it properly. But I really appreciate the thought. For others, coming here, I have resolved the above issue and explained it [here](http://stackoverflow.com/a/39128152/6704455).
